apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-credentials
data:
  credentials: |
    [default]
    aws_access_key_id = ASIA3SEE4D6UXP7K2QNH
    aws_secret_access_key = xbUeVgPkbBmx+N/spGZyFkkb7y8iyBKJn3KMmJHw
    aws_session_token = FwoGZXIvYXdzEBMaDJF/9xd305tKEP6iBiLVAUu1rTIjVgZwyn+c12Stz9I4NHoanjUhXloxi2FhkDEU/pJwZgIlMHA+KeZTDn1MB0+XaDYrL0VLowT98p317aG1FbhPN75mLaR/W1LJy/TfsvXCKM9wBAySp+oj1RlOJH86PONLRa5irxVQ0puAWqYVvO2K6cUgqa2eiQ4CYWNQnro8EaEn4kX3TZcctySp6EpDS+BcFLFYAePmJTUqwj72cCmhVT+V/pecyn/tyy/48fKwxTmkjtNk2ipNuY1lqnhHtEPYE8g4pCNrnZXltIC7Qofbbiji7++ZBjIt+zyLUySIzs/+kF8Kp+rC60LZOe5YHZIy2US4cxCEviv5ED6uLZ6mpe3IHJBX
  

