apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: 3rwinn/udagram-api-user:v1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-credentials
      volumes:
        - name: aws-credentials
          configMap:
            name: aws-credentials